matrix:
  include:
    - stage: Lint
      os: linux
      language: node_js
      node_js: "10"
      env:
        - Lint="eslint"
      before_script: npm i
      script: "./node_modules/.bin/eslint src/"
    - stage: Build Android
      os: linux
      language: node_js
      node_js: "10"
      env:
        - OS="Linux"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - echo no | npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build android --path demo
    - os: windows
      language: node_js
      node_js: "10"
      env:
        - OS="Windows"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build android --path demo
    - os: osx
      language: node_js
      node_js: "10"
      env:
        - OS="MacOS"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - echo no | npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build android --path demo
    - stage: Release Build Android
      os: linux
      language: node_js
      node_js: "10"
      env:
        - OS="Linux"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - echo no | npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
        - echo $KEYSTORE_BASE64_ENCODED > ~/test1111.txt
        - base64 --decode ~/test1111.txt > ~/Telerik1111.keystore
      script: tns build android --path demo --release --for-device --key-store-path ~/Telerik.keystore --key-store-password t3l3r1kad --key-store-alias Telerik --key-store-alias-password t3l3r1kad
    - os: windows
      language: node_js
      node_js: "10"
      env:
        - OS="Windows"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
        - echo $KEYSTORE_BASE64_ENCODED > ~/test1111.txt
        - base64 --decode ~/test1111.txt > ~/Telerik1111.keystore
      script: tns build android --path demo --release --for-device --key-store-path ~/Telerik.keystore --key-store-password t3l3r1kad --key-store-alias Telerik --key-store-alias-password t3l3r1kad
    - os: osx
      language: node_js
      node_js: "10"
      env:
        - OS="MacOS"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - echo no | npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
        - echo $KEYSTORE_BASE64_ENCODED > ~/test1111.txt
        - base64 --decode ~/test1111.txt > ~/Telerik1111.keystore
      script: tns build android --path demo --release --for-device --key-store-path ~/Telerik.keystore --key-store-password t3l3r1kad --key-store-alias Telerik --key-store-alias-password t3l3r1kad
    - stage: Build iOS
      os: linux
      language: node_js
      node_js: "10"
      env:
        - OS="Linux"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - echo no | npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build ios --path demo
    - os: windows
      language: node_js
      node_js: "10"
      env:
        - OS="Windows"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build ios --path demo
    - os: osx
      language: node_js
      node_js: "10"
      env:
        - OS="MacOS"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - echo no | npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build ios --path demo


 - stage: Release Build iOS
      os: linux
      language: node_js
      node_js: "10"
      env:
        - OS="Linux"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - echo no | npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build ios --path demo --env.uglify --env.report --env.aot --release --for-device
    - os: windows
      language: node_js
      node_js: "10"
      env:
        - OS="Windows"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build ios --path demo --env.uglify --env.report --env.aot --release --for-device
    - os: osx
      language: node_js
      node_js: "10"
      env:
        - OS="MacOS"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - echo no | npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build ios --path demo --env.uglify --env.report --env.aot --release --for-device
