matrix:
  include:
    - stage: Lint
      os: linux
      language: node_js
      node_js: "10"
      env:
        - Lint="eslint"
      before_script: npm i
      script: "./node_modules/.bin/eslint src/"
    - stage: Build Android
      os: linux
      language: node_js
      node_js: "10"
      env:
        - OS="Linux"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - echo no | npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build android --path demo
    - os: windows
      language: node_js
      node_js: "10"
      env:
        - OS="Windows"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build android --path demo
    - os: osx
      language: node_js
      node_js: "10"
      env:
        - OS="MacOS"
      before_script:
        - git config --global user.email "remote-builds-travis-ci@nativescript.org"
        - git config --global user.name "Remote Builds Travis CI"
        - echo no | npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - cd demo && npm i
      script: tns build android --path demo
