# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/android:api-29-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: "{{PROJECT_DIR}}"

    steps:
      # GLOBAL OPERATIONS

      # setup NPM
      - run: echo 'export PATH=~/npm_prefix/bin:$PATH' >> $BASH_ENV
      - run: npm config set prefix ~/npm_prefix

      # setup TNS
      - restore_cache:
          keys:
            - global-modules-linux-{{CLI_VERSION}}
      - run: tns --version || npm i -g nativescript@{{CLI_VERSION}}
      - save_cache:
          paths:
            - ~/npm_prefix
          key: global-modules-linux-{{CLI_VERSION}}
      - run: tns usage-reporting disable
      - run: tns error-reporting disable

      - checkout

      # NODE PACKAGES
      - run: npm install
      - run: npm rebuild
      - restore_cache:
          key: gems-linux-{{ checksum "Gemfile" }}
      # INSTALL GEMS (fastlane)
      - run: bundle config set path 'vendor/bundle'
      - run: bundle install
      - save_cache:
          key: gems-linux-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle

      - restore_cache:
          key: gradle-{{ checksum "package.json" }}

      - run:
          name: Fastlane
          command: bundle exec fastlane android build

      - save_cache:
          key: gradle-{{ checksum "package.json" }}
          paths:
            - ~/.gradle

      # Expose artifacts
      - store_artifacts:
          path: "{{OUTPUT_DIR}}"
      # CACHE
      # - save_cache:
      #     # TODO: add platforms cache?
      #     paths:
      #       - node_modules
      #       - ~/.gradle/
      #     key: v1-dependencies-{{ checksum "package.json" }}
